export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SET_ID = "USER_SET_ID";

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"


export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_RECEIVED = "USER_PROFILE_RECEIVED";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";


export const ARTICLE_LIST_REQUEST = "ARTICLE_LIST_REQUEST";
export const ARTICLE_LIST_RECEIVED = "ARTICLE_LIST_RECEIVED";
export const ARTICLE_LIST_ERROR = "ARTICLE_LIST_ERROR";


export const ARTICLE_REQUEST = "ARTICLE_REQUEST";
export const ARTICLE_RECEIVED = "ARTICLE_RECEIVED";
export const ARTICLE_ERROR = "ARTICLE_ERROR";
export const ARTICLE_UNLOAD = "ARTICLE_UNLOAD";
export const ARTICLE_REMOVED = "ARTICLE_REMOVED";
export const ARTICLE_ADDED = "ARTICLE_ADDED";
export const ARTICLE_UPDATED = "ARTICLE_UPDATED";


export const FILE_REMOVED = "FILE_REMOVED";

export const alertConstants = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR",
};
